### ISSUE TITLE
Newer than v90.* Android WebView messes up Yuzu homepage, speed dial and page text size.

### ISSUE THREAD

**Issue by ksuuk** [Hazuki0x0/YuzuBrowser#213]
Xperia X, stock Oreo.

Edit: Seems this is related to Android WebView latest updates, as with Android WebView v90.* everything works fine, but with any newer Android WebView version (v91.* or v92.*) Yuzu and also Berry are acting weirdly.

At some time Yuzu is acting weirdly. To be sure that it's not my settings, I resetted Yuzu and make some test. After I launch Yuzu, default homepage opens:
![1](https://user-images.githubusercontent.com/26193002/121931340-2a8ca100-cd4c-11eb-9074-85079ef6414e.png)

I type "abba" into URL bar and click enter, new page opens: 
![2](https://user-images.githubusercontent.com/26193002/121931356-2f515500-cd4c-11eb-9ad0-81f0f8fcaf7d.png)

but the page text size is very small, when I click back, the default homepage opens but now also it's text size is smaller then before:
![3](https://user-images.githubusercontent.com/26193002/121931375-337d7280-cd4c-11eb-8d47-fee72ed08266.png)

When the search result "abba" page is open, I kill Yuzu, launch Yuzu again and the page text sise is again normal:
![4](https://user-images.githubusercontent.com/26193002/121931388-38422680-cd4c-11eb-8cc7-d8ac3cfe6aac.png)

At the Yuzu homepage command "Close all (tabs)" brings back normal text size at the Yuzu homepage.

Also noticed, that "settings > speed dial settings > item text size" does nothing, as homepage speed dial item text size is based page text size and I can't completely disable speed dial item text.

**Comment by StOrmCatz** [comment]
I can confirm this issue.  However,  this doesn't seem to be specific to Yuzu.  I've tested other browsers that depend on Google's Android System Webview, and the issue is happening for them too.  It appears it might be a bug that was introduced in the newer versions of Webview.

I've been playing around trying to understand when it happens,  and it seems to commonly occur when one changes the URL to a new site and it only applies to the first page that is loaded?  Subsequent pages on the same site seems to respect the configured page text size. It also seems like the Webview component is aware of configured page text size since if you reapply the **same** text size nothing happens (remains small),  but if you change the size it rerenders everything correctly. 

I've been trying to figure out a workaround for this until Google hopefully addresses this in Webview. It's not perfect,  but I created a version that performs a rerender on that first page, so you'll see the text jump from the incorrect smaller size to the configured expected size. If you are interested in trying it out,  my version is here: https://mega.nz/file/KJhj2SaZ#ESDk6ogTjkVGv6FufV0jtiAAFRp7g-zL5nX2zJAr1mE

**Comment by ksuuk** [comment]
@StOrmCatz 

At the moment I refuse to upgrade Webview and Yuzu works (however Berry doesn't and developer doesn't care). Same issue happens, when I switch from Webview to newer Chrome.

What Android version are You using? Webview is a important software and as only we here are noticing this bug, I am afraid that this may be related to older Android versions and with some browsers, including Chrome only and Google isn't aware of this bur or won't fix it.

BTW, Yuzu can,t save Your file, after clicking save file, opens empty page with URL about:blank#blocked

**Comment by StOrmCatz** [comment]
I have several devices, one on Android 9, 10, and 11.  The issues exists on all of them so I don't think it's due to older Android versions. 

As to being unable to download the file,  it seems you've uncovered another potential issue with Yuzu.  You'll need to use a different browser to work around it.

**Comment by ksuuk** [comment]
@StOrmCatz 

Can You please report this bug to Google? 

I don't know the right place, maybe to some or to all sites:

https://source.android.com/setup/contribute/report-bugs
https://support.google.com/android/community?hl=en
https://groups.google.com/a/chromium.org/g/android-webview-dev

**Comment by StOrmCatz** [comment]
I'm not familiar with the right place either.  This looks like another potential area: https://bugs.chromium.org/p/chromium/issues/list?q=webview

Did you get a chance to look through any of the lists to see if it might've already been reported?

**Comment by ksuuk** [comment]
@StOrmCatz 

Seems correct place, I made a quick overview, but didn't notice that this bug is already reported.
So please report (as You dug deeper and can explain better) it.

**Comment by StOrmCatz** [comment]
Good news! I'm no longer seeing this issue with the recently released Android Webview 92.0.4515.115. Have a look and see if it's resolved for you @ksuuk

**Comment by ksuuk** [comment]
@StOrmCatz 

I can confirm that Andoid WebWiev 92.0.4515.115 fixed this issue.
Changlog - https://chromium.googlesource.com/chromium/src/+log/92.0.4515.105..92.0.4515.115?pretty=fuller&n=10000

**Comment by ksuuk** [comment]
Andoid WebWiev 92.0.4515.115 fixed this issue.
