### ISSUE TITLE
2 suggestions

### ISSUE THREAD

**Issue by taka-hkd** [hazuki0x0/YuzuBrowser#5]
1. How about adding bookmark entries in search suggestions? Many other browsers are doing so and this would be helpful for users who has so many bookmarks.

2. Can the browser insert HTTP headers? By adding some headers to HTTP packets and sending traffic to proxy.googlezip.net:443, users will be able to use Google Compression Proxy.
More info about the proxy written in Japanese:
https://otya.me/tech/dev/google-compress-other-browser__trashed/

I suggest that you should add the second option ONLY TO GITHUB DISTRIBUTED VERSION, otherwise google will delete your app from play store.

**Comment by taka-hkd** [comment]
By the way, thanks for the good app!

**Comment by hazuki0x0** [comment]
1. I will probably implement this and #4 No.2. However, it takes time to implement because there are already many suggestions.
2. It's very interested, but it has problems. It is impossible to change proxy by the browser app on Android 6.0 or higher. And, due to the problem of rights, I cannot implement it.
However, it seems that we can add headers.(unconfirmed)

**Comment by taka-hkd** [comment]
I understood. If no one comments on this issue, I'll close it in a few days.

Anyways, thanks for the app!
